name: CI - Symfony Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: subworld
          MYSQL_USER: app
          MYSQL_PASSWORD: securepassword
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set Up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, xml, zip, intl, pdo, pdo_mysql
        coverage: none
    - name: Install Dependencies
      run: |
        composer install --no-progress --no-suggest --prefer-dist
        cp .env.test .env.local
    - name: Run Database Migrations
      run: php bin/console doctrine:migrations:migrate --no-interaction
    - name: Run Symfony Tests
      run: vendor/bin/phpunit